# Generated by Django 4.0.5 on 2022-06-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_employee_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('management', 'management'), ('sales', 'sales'), ('support', 'support')], max_length=10),
        ),
    ]
