# Generated by Django 4.0.5 on 2022-07-07 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_event_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contract'),
        ),
    ]
